[package]
name = "hotkeys"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
usage = { package = "usage-rs", version = "6" }
libc = "0.2"
notify = { version = "6", default-features = false, features = ["macos_kqueue"] }
toml = "0.8"
objc2-foundation = { version = "0.2", features = ["NSDate", "NSRunLoop", "NSString", "NSThread", "NSURL"] }
objc2-app-kit = { version = "0.2", features = ["NSApplication", "NSEvent", "NSResponder", "NSRunningApplication", "NSWorkspace", "block2"] }
